name: CI


on:
  push:
    branches:
      branches: Nakai
  pull_request: 
    branches: Nakai

  workflow_dispatch:

jobs:

  testContainer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -t teste .

    - name: Run
      run: docker run --name test -d -p 8000:8000 teste
    - name: Get logs
      run: docker logs test
    - name: Sleep for 5 seconds
      run: sleep 5
    - name: Test container
      run: echo "::set-output name=status::$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8000/teste)"
    - uses: nick-invision/assert-action@v1
      with:
        expected: 200
        actual: "$(::get-output name=status)"